# Generated by Django 3.1.1 on 2020-09-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200925_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='instagram_id',
            field=models.CharField(max_length=50),
        ),
    ]
